import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/** group -> key -> value. Two levels; the CSS name is `--zrm-<group>-<key>`. */
export type Tokens = Record<string, Record<string, string>>
export type ThemeOverrides = Record<string, Record<string, string>>

export interface BuildOptions {
  base: Tokens
  /** Named theme overrides over `base`. Only keys that base defines are allowed. */
  themes: Record<string, ThemeOverrides>
  defaultTheme: string
  outDir: string
  /** Extra CSS written at the top of `theme-<name>.css`, e.g. `@font-face` rules. */
  extraThemeCss?: Record<string, string>
}

/** Breakpoints and the fluid range are global: queries cannot read custom properties. */
const GLOBAL_GROUPS = ['breakpoint']
const RAMP_STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]

export function flattenTokens(tokens: Tokens): Record<string, string> {
  const flat: Record<string, string> = {}
  for (const [group, entries] of Object.entries(tokens)) {
    for (const [key, value] of Object.entries(entries)) flat[`${group}-${key}`] = value
  }
  return flat
}

function assertOverrides(base: Tokens, name: string, overrides: ThemeOverrides): void {
  for (const [group, entries] of Object.entries(overrides)) {
    if (GLOBAL_GROUPS.includes(group)) {
      throw new Error(`theme "${name}" overrides "${group}", which is global (queries cannot read custom properties)`)
    }
    for (const key of Object.keys(entries)) {
      if (!(key in (base[group] ?? {}))) {
        throw new Error(`theme "${name}" sets ${group}.${key}, which base does not define`)
      }
    }
  }
}

export function mergeTokens(base: Tokens, overrides: ThemeOverrides): Tokens {
  const merged: Tokens = {}
  for (const [group, entries] of Object.entries(base)) merged[group] = { ...entries, ...(overrides[group] ?? {}) }
  return merged
}

const declarations = (flat: Record<string, string>) =>
  Object.entries(flat).map(([k, v]) => `  --zrm-${k}: ${v};`).join('\n')

function themeCss(name: string, flatOwn: Record<string, string>, flatFull: Record<string, string> | null, extra = ''): string {
  const parts: string[] = []
  if (extra) parts.push(extra.trimEnd())
  if (flatFull) parts.push(`:root {\n${declarations(flatFull)}\n}`)
  parts.push(`:root[data-theme="${name}"] {\n${declarations(flatOwn)}\n}`)
  return `/* generated by @motor-cms/ui-design-tokens, do not edit */\n${parts.join('\n\n')}\n`
}

const px = (value: string) => Number.parseFloat(value)

function fluid(role: string, prop: 'text' | 'leading', fluidMin: number, fluidMax: number): string {
  const lo = `var(--zrm-${prop}-${role}-min)`
  const hi = `var(--zrm-${prop}-${role}-max)`
  const slope = `((100vw - ${fluidMin}px) / ${fluidMax - fluidMin})`
  return `clamp(calc(${lo} * 1px), calc(${lo} * 1px + (${hi} - ${lo}) * ${slope}), calc(${hi} * 1px))`
}

function tailwindTheme(base: Tokens): string {
  const lines: string[] = []
  const map = (namespace: string, group: string, filter: (key: string) => boolean = () => true) => {
    for (const key of Object.keys(base[group] ?? {})) {
      if (filter(key)) lines.push(`  --${namespace}-${key}: var(--zrm-${group}-${key});`)
    }
  }
  map('color', 'color', (k) => !k.endsWith('-rgb') && !k.startsWith('admin-'))
  map('font', 'font')
  map('font-weight', 'weight')
  map('spacing', 'space')
  map('radius', 'radius')
  map('shadow', 'shadow')
  map('ease', 'motion', (k) => k.startsWith('ease-'))
  lines.push(`  --container-page: var(--zrm-container-max);`)

  const bp = base.breakpoint ?? {}
  const fluidMin = px(bp['fluid-min'])
  const fluidMax = px(bp['fluid-max'])
  for (const key of Object.keys(base.text ?? {}).filter((k) => k.endsWith('-min'))) {
    const role = key.slice(0, -4)
    lines.push(`  --text-${role}: ${fluid(role, 'text', fluidMin, fluidMax)};`)
    lines.push(`  --text-${role}--line-height: ${fluid(role, 'leading', fluidMin, fluidMax)};`)
  }

  // Literal values: media and container queries cannot read variables.
  const named = Object.entries(bp).filter(([k]) => !k.startsWith('fluid-'))
  for (const [k, v] of named) lines.push(`  --breakpoint-${k}: ${v};`)
  for (const [k, v] of named) lines.push(`  --container-${k}: ${v};`)

  return `/* generated by @motor-cms/ui-design-tokens, do not edit */\n@theme inline {\n${lines.join('\n')}\n}\n`
}

function adminBridge(merged: Tokens): string {
  const lines = RAMP_STEPS.map((step) => {
    const value = merged.color?.[`admin-primary-${step}`]
    if (!value) throw new Error(`color.admin-primary-${step} is missing`)
    return `  --color-motor-primary-${step}: ${value};`
  })
  return `/* generated by @motor-cms/ui-design-tokens, do not edit */\n:root {\n${lines.join('\n')}\n}\n`
}

/** Writes theme-<name>.css per theme, theme.css and admin-bridge.css; returns the written paths. */
export function buildTokens(options: BuildOptions): string[] {
  const { base, themes, defaultTheme, outDir, extraThemeCss = {} } = options
  if (!(defaultTheme in themes)) throw new Error(`default theme "${defaultTheme}" is not in the theme map`)
  for (const [name, overrides] of Object.entries(themes)) assertOverrides(base, name, overrides)

  mkdirSync(outDir, { recursive: true })
  const written: string[] = []
  const write = (file: string, content: string) => {
    const path = join(outDir, file)
    writeFileSync(path, content)
    written.push(path)
  }

  const merged = mergeTokens(base, themes[defaultTheme])
  for (const [name, overrides] of Object.entries(themes)) {
    const full = name === defaultTheme ? flattenTokens(merged) : null
    write(`theme-${name}.css`, themeCss(name, flattenTokens(overrides as Tokens), full, extraThemeCss[name]))
  }
  write('theme.css', tailwindTheme(base))
  write('admin-bridge.css', adminBridge(merged))
  return written
}
