export const packageName = '@motor-cms/ui-design-recipes'
export { tv, twMergeConfig } from './tv.js'
export { blockBase } from './base.js'
export { headlineAtom } from './headline-atom.js'
export { paragraphAtom } from './paragraph-atom.js'
export { buttonAtom } from './button-atom.js'
export { cardComponent } from './card-component.js'
